<header>
	<h3>Terms of Service</h3>
	<p>Describe what you can and can't do on Pulsir, and what we can do about it.</p>
</header>

<article>
	* The following legal speak governs all use of the Pulsir website and all content, services and products available at or through the website. 
<br>
<blockquote><b>very legal
<br>&nbsp; much terms
<br>&nbsp; so lawyer
<br>many conditions
<br>&nbsp; wow</b>
<br>
</blockquote>
<br>* Even if you usually just click Accept, it's a really good idea to read this, just to make sure we won't sell your newborn. (spoiler: we won't)
<br>Also, this document is licensed under <a href="http://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0</a>, so feel free to use it wherever you want. If you have questions, concerns or suggestions about these terms, please leave a reply here.
<br>
<br>1. By accessing or using any part of Pulsir, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access or use Pulsir. :( 
<br>
<br>By using Pulsir, you also agree to the Pulsir <a href="http://pulsir.eu/privacy">Privacy policy</a>. 
<br>
<br>2. Pulsir reserves the right to change the terms of service or the privacy policy, or any other document governing your use of the site, at any given moment, with prior notice for major changes. You'll be notified when we change the TOS, either via email or the Pulsir site.
<br>
<br>3. If you create a Pulsir account, you are responsible for maintaining its security,&nbsp; and you are fully responsible for all activities that occur in connection to your account. Pulsir may change parts of your profile to follow the TOS (you'll be informed before that happens) or in some cases, disable or delete it with or without your permission.
<br>
<br>4. You are entirely responsible for the content you post on Pulsir and any harm originating from it. By posting content on Pulsir, you warrant that your content:
<br>* does not violate international or Croatian laws, including, but not limited to, copyright and trademark laws, anti-spam laws, patent and trade secret laws and so on;
<br>* does not contain or install malware or other harmful or destructive content;
<br>* is not spam or automatically generated content, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or their search engine rankings, or link to unlawful acts (such as phishing) or mislead visitors as to the source of the material (such as spoofing);
<br>* is not pornographic, does not contain threats or incite violence, and does not violate rights of others (for instance, doxxing);
<br>* is not misleading in a way that makes you appear to be a person, business or an entity that you're not.
<br>
<br>5. You retain ownership of all copyrights and any other intellectual property rights in your content. Pulsir retains ownership of intellectual property rights in all content not generated by users. Pulsir can't and will not use or sell your content without your written approval.
<br>
<br>6. Pulsir may terminate your access to all or any part of Pulsir at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this agreement or your Pulsir account (if you have one), you can simply discontinue using Pulsir.
<br>
<br>7. By posting your content to Pulsir you grant us a royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide license to reproduce, prepare derivative works, distribute copies, perform, or publicly display your content in any medium (we should phrase this better) and for any purpose, including commercial purposes, and to authorize others to do so. 
<br>
<br>
<blockquote>Wait, what does this mean?! They get to own my content even though they state at #5 they don't? Um...
<br>
</blockquote>
<br>
<br>
<blockquote> The individual components mean this:
<br>
<br>&nbsp; royalty-free: we don't have to pay you to display the post/comment that you posted
<br>&nbsp; perpetual: the right to display what you posted doesn't disappear after some specified time
<br>&nbsp; irrevocable: once you posted it, you can't just say "hey wait, no, you can't display that." (In practice though, we allow you to delete it, but in case we do not successfully delete it or remove it fast enough, we wouldn't want there to be legal liability associated with that)
<br>&nbsp; non-exclusive: THIS IS IMPORTANT - non-exclusive means that you retain the rights to what you posted, i.e. you can still publish it elsewhere. We are just claiming a license to display it in addition to your own rights. This is something that has come up a lot - people often wonder when we claim such a wordy and broad license to their contributions whether they still retain rights to it: you absolutely do. You can take your own stuff and make it into a book, or republish it on your website, or anything you want. We just retain a non-exclusive license to be able to display the content you wrote
<br>&nbsp; unrestricted, worldwide: these rights aren't restricted to e.g. Croatia, because anyone in the world might use [Pulsir], so we need to be able to do that in any country.
<br>&nbsp; derivative works, copies, publicly display: thumbnails are derivative works, and snippets can be as well. [as for
<br>&nbsp; authorizing others to do so: we may need to pass the content through any number of service providers in the course of doing business. The biggest one is CDNs or hosters, who redistribute/cache our content through edge networks to servers closer to you in order to reduce latency and load on our origin servers.
<br>
</blockquote>
<br>8. Pulsir is provided <i>as is</i>. Pulsir&nbsp; disclaims all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. 
</article>
